[package]
name = "rust_game_engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "parser"
path = "src/parser.rs"

[dependencies]
regex = "1"
eframe = "0.23"
winapi = { version = "0.3", features = ["windef", "winuser"] }