[package]
name = "calculatorcalculator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "tcrate"
path = "src/lib.rs"

[dependencies]
regex = "1"
eframe = "0.23"
winapi = { version = "0.3", features = ["windef", "winuser"] }